# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'BPBLEDemo' do
  use_frameworks!
  inhibit_all_warnings!
  
  # Test Local
  pod 'BPBLESDK-S02-iOS', :path => '../'
  # Test Pod
#  pod 'BPBLESDK-S02-iOS', :git => 'https://github.com/BodyPlusTechnology/BPBLESDK-S02-iOS.git'
  pod 'Masonry', '1.1.0'
  pod 'MBProgressHUD', '~> 1.0.0'
  pod 'YYKit'
  pod 'iOSDFULibrary', '~> 4.3.0'
  pod 'SSZipArchive', '~> 2.1.4'
end
